name: msgraph_cli_$(Date:yyyyMMdd)

stages:
- stage: BuildPackages
  displayName: 'Build Packages'
  jobs:
  - job: BuildMSIPackage
    displayName: "Build MSI Package"
    pool:
      vmImage: 'vs2017-win2016'
    strategy:
      matrix:
        Python37:
          python.version: '3.7'
    steps:
      - task: UsePythonVersion@0
        displayName: 'Use Python $(python.version)'
        inputs:
          versionSpec: '$(python.version)'
      - script: |
          python -m pip install --upgrade pip
          pip install wheel
        displayName: 'Upgrade pip and install wheel'
      - script: |
          python build_scripts/build_extensions.py
        displayName: 'Build cli extensions'
      - task: CmdLine@2
        displayName: 'Build msgraph-cli'
        inputs:
          workingDirectory: $(Agent.BuildDirectory)
          script: |
            python setup.py sdist bdist_wheel
            set CLI_VERSION=$(CLI_VERSION)
            set
            build_scripts/windows/scripts/build.cmd
      - task: PublishPipelineArtifact@0
        displayName: 'Publish msgraph-cli artifact'
        inputs:
          TargetPath: 'build_scripts/windows/out'
          ArtifcatName: msgraph-msi
#   - job: BuildDebianPackage
#     displayName: "Build Debian Package"

# - stage: DeployPackages
#   displayName: 'Deploy Packages'
#   jobs:
#   - deployment: DeployToChocolatey
#     displayName: "Deploy MSI package to Chocolatey"
#   - deployment: DeployToApt
#     displayName: "Deploy Debian package to apt repository"
