name: msgraph_cli_$(Build.BuildId)

stages:
- stage: BuildPackages
  displayName: 'Build Packages'
  jobs:
  - job: BuildMSIPackage
    displayName: "Build MSI Package"
    pool:
      vmImage: 'vs2017-win2016'
    strategy:
      matrix:
        Python37:
          python.version: '3.7'
    steps:
      - task: UsePythonVersion@0
        displayName: 'Use Python $(python.version)'
        inputs:
          versionSpec: '$(python.version)'

      - script: |
          python -m pip install --upgrade pip
          pip install wheel
        displayName: 'Upgrade pip and install wheel'

      - script: |
          python build_scripts/build_extensions.py
        displayName: 'Build cli extensions'

      - task: CmdLine@2
        displayName: 'Build msgraph-cli'
        inputs:
          script: |
            python setup.py sdist bdist_wheel
            set CLI_VERSION=$(CLI_VERSION)
            set
            cd build_scripts/windows/scripts
            build.cmd

      - task: PublishPipelineArtifact@1
        displayName: 'Publish msgraph-cli artifact'
        inputs:
          TargetPath: 'build_scripts/windows/out/'
          ArtifactName: msgraph-msi


  - job: BuildDebianPackage
    displayName: "Build Debian Package"
    pool:
      vmImage: 'ubuntu-18.04'
      strategy:
        matrix:
          Python37:
            python.version: '3.7'
    steps: 
      - task: UsePythonVersion@0
        displayName: 'Use Python $(python.version)'

      - script: |
          python -m pip install --upgrade pip
          pip install wheel
        displayName: 'Upgrade pip and install wheel'

      - bash: |
          python build_scripts/build_extensions.py
        displayName: 'Build cli extensions'          

      - bash: |
          chmod u+x build_scripts/debian/build.sh
          chmod u+x build_scripts/debian/prepare.sh
          
          docker build --target build-env -f ./build_scripts/debian/Dockerfile -t microsoft/msgraph-cli:ubuntu-builder .
          docker run --name debian microsoft/msgraph-cli:ubuntu-builder

          mkdir -p debian/out/

          docker cp debian:/msgraph-cli_all.deb ./debian/out/
        displayName: 'Build docker image'

      - task: PublishPipelineArtifact@1
        displayName: 'Publish msgraph-cli debian artifact'
        inputs:
          TargetPath: 'debian/out'
          ArtifactName: msgraph-deb




- stage: ReleaseToGithub
  jobs:
    - job: ReleaseToGithub
      displayName: "Release to GitHub"
      pool:
        vmImage: 'ubuntu-18.04'
      steps:
        - task: DownloadPipelineArtifact@2
          inputs:
            source: current

        - bash: |
            ls -la
            ls $(Pipeline.Workspace)
          displayName: 'Directory structure'
    
        - task: GitHubRelease@0
          inputs:
            gitHubConnection: 'ddyett'
            repositoryName: 'microsoftgraph/msgraph-cli'
            tagSource: 'manual'
            tag: '$(Build.BuildNumber)'
            assets: |
              '$(Pipeline.Workspace)/msgraph-msi/*.msi'
              '$(Pipeline.Workspace)/msgraph-deb/*.deb'


